apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: cert-manager
spec:
  secretName: wildcard-cert-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
    - 'kops.infra.devops.starburstdata.net'
    - '*.kops.infra.devops.starburstdata.net'
  issuerRef:
    name: acme
    kind: ClusterIssuer
